### PR TITLE
feat(proxy): add /:token endpoints for chains from the EVM config

### PR DESCRIPTION
**Pull request by tukan**

### CODE REVIEW

**Comment by polachok** [comment]
Looks complicated, wouldn't it be possible to use [to_service_builder](https://docs.rs/jsonrpsee-server/0.24.0/jsonrpsee_server/struct.ServerBuilder.html#method.to_service_builder) ?
Smth like:

```rust
    let make_module = |chain_id| {
        let eth = EthApiImpl::new(
            pool.clone(),
            solana.clone(),
            chain_id,
            executor.clone(),
            mp_gas_prices.clone(),
        );
        let mut module = jsonrpsee::server::RpcModule::new(());
        module
            .merge(<EthApiImpl as EthApiServer>::into_rpc(eth.clone()))
            .expect("no conflicts");

        module.remove_method("eth_getTransactionReceipt");

        module
            .merge(<EthApiImpl as NeonEthApiServer>::into_rpc(eth.clone()))
            .expect("no conflicts");

        module
            .merge(<EthApiImpl as EthFilterApiServer>::into_rpc(eth.clone()))
            .expect("no conflicts");

        module.remove_method("eth_getLogs");
        module
            .merge(<EthApiImpl as NeonFilterApiServer>::into_rpc(eth.clone()))
            .expect("no conflicts");
        module
    };

    use tower::Service;
    let (stop_handle, _server_handle) = jsonrpsee::server::stop_channel();
    let server_builder = jsonrpsee::server::Server::builder().to_service_builder();
    let listener = tokio::net::TcpListener::bind(&opts.listen).await.unwrap();
    tracing::info!("Listening on {}", opts.listen);
    loop {
        let (stream, _) = listener.accept().await.unwrap();
        let server_builder = server_builder.clone();
        let stop_handle = stop_handle.clone();
        let svc = tower::service_fn(move |req: http::Request<_>| {
            let uri = req.uri().path().split('/').next();
            let chain_id = if uri == Some("neon") { 1 } else { 1312 }; // whatever routing should be done
            let module = make_module(chain_id);
            let mut svc = server_builder.build(module.clone(), stop_handle);
            async move { svc.call(req).await }
        });
        tokio::spawn(jsonrpsee::server::serve_with_graceful_shutdown(
             stream,
             svc,
             stop_handle.clone(),
        ))
    }
```

**Comment by tukan** [comment]
@polachok I don't have a strong opinion on which way is better. I thought about using tower's `service_fn` however I didn't like the idea of defining a module for each request we have, as I believe we can consider the set of evm tokens to be static hence no need to re-create all the methods for each request. So I ended up copy-pasting their own proxy layer and adapting to our case.

**Comment by tukan** [comment]
@polachok @00nktk `jsonrpsee::server::serve_with_graceful_shutdown` and fancier api is available in `jsonrpsee` 0.24 and we're on 0.22, and `reth` is not updated to 0.24 yet. I'd probably leave it as it is for now, as this code's using their standard middleware api for 0.22. We can update it when 0.24 will be available for us

**Comment by tukan** [comment]
@polachok @00nktk `jsonrpsee::server::serve_with_graceful_shutdown` is available in `jsonrpsee` 0.23 and we're on 0.22 with @polachok's nice addition. I can update it to 0.23, but I will also need to update `reth` to at least `1.0.0`. But new `reth` depends on `metrics v0.23.0`, which depends on `ahash ^0.8.8`  while `solana-sdk = "^1.17.34"` depends on `ahash = "=0.8.5"`. We can of course patch `metrics`, but I would like to avoid patching anything unless it's really necessary.

`serve_with_graceful_shutdown` is not very beautiful as well (in case we want to copy-paste it to our code base):

```rust
pub async fn serve_with_graceful_shutdown<S, B, I>(
	io: I,
	service: S,
	stopped: impl Future<Output = ()>,
) -> Result<(), BoxError>
where
	S: tower::Service<http::Request<hyper::body::Incoming>, Response = http::Response<B>> + Clone + Send + 'static,
	S::Future: Send,
	S::Response: Send,
	S::Error: Into<BoxError>,
	B: http_body::Body<Data = hyper::body::Bytes> + Send + 'static,
	B::Error: Into<BoxError>,
	I: tokio::io::AsyncRead + tokio::io::AsyncWrite + Send + Unpin + 'static,
{
	let service = hyper_util::service::TowerToHyperService::new(service);
	let io = TokioIo::new(io);

	let builder = hyper_util::server::conn::auto::Builder::new(TokioExecutor::new());
	let conn = builder.serve_connection_with_upgrades(io, service);

	tokio::pin!(stopped, conn);

	match future::select(conn, stopped).await {
		// Return if the connection was completed.
		Either::Left((conn, _)) => conn,
		// If the server is stopped, we should gracefully shutdown
		// the connection and poll it until it finishes.
		Either::Right((_, mut conn)) => {
			conn.as_mut().graceful_shutdown();
			conn.await
		}
	}
}
```

Yes, the proxy mechanism in `jsonrpsee` looks a bit ugly, but I'd rather keep it as it is until I will be able to update to the newer `jsonrpsee` without patches.

**Review by polachok — APPROVED** [review]

**Pull request merged**
